export default {
  id: "charm",
  alias: "charm",
  aliases: ["hyper-charm", "charm-land"],
  uiAlias: "charm",
  display: {
    name: "Charm",
    icon: "auto_awesome",
    color: "#E040FB",
    textIcon: "CH",
    website: "https://hyper.charm.land",
    notice: {
      apiKeyUrl: "https://hyper.charm.land",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://hyper.charm.land/v1/chat/completions",
    validateUrl: "https://hyper.charm.land/v1/models",
    usage: {
      url: "https://hyper.charm.land/v1/credits",
    },
  },
  models: [
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "glm-5.3", name: "GLM 5.3" },
    { id: "glm-5.3-flash", name: "GLM 5.3 Flash" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2-thinking", name: "Kimi K2 Thinking" },
    { id: "qwen3.8-max", name: "Qwen 3.8 Max" },
    { id: "qwen3.8-flash", name: "Qwen 3.8 Flash" },
    { id: "qwen3.8-2.4t-a95b", name: "Qwen 3.8 2.4T" },
    { id: "qwen3.8-27b", name: "Qwen 3.8 27B" },
    { id: "qwen3.7-max", name: "Qwen 3.7 Max" },
    { id: "qwen3.7-plus", name: "Qwen 3.7 Plus" },
    { id: "qwen3.7-flash", name: "Qwen 3.7 Flash" },
    { id: "qwen3.6-max", name: "Qwen 3.6 Max" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus" },
    { id: "qwen3.6-flash", name: "Qwen 3.6 Flash" },
    { id: "qwen3-coder-480b-a35b-instruct-int4-mixed-ar", name: "Qwen3 Coder 480B" },
    { id: "qwen3-next-80b-a3b-instruct", name: "Qwen3 Next 80B" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "gpt-oss-120b", name: "GPT-OSS 120B" },
    { id: "inkling", name: "Inkling" },
    { id: "gemma-4-26b-a4b-it", name: "Gemma 4 26B" },
    { id: "llama-4-maverick-17b-128e-instruct-fp8", name: "Llama 4 Maverick" },
    { id: "llama-3.3-70b-instruct", name: "Llama 3.3 70B" },
  ],
  passthroughModels: true,
  features: {
    usage: true,
    usageApikey: true,
  },
};
